// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMSystem.Server.Entities
{
    /// <summary>
    /// 用户实体
    /// </summary>
    public class User:BaseEntity
    {
        /// <summary>
        /// 账号
        /// </summary>
        [SugarColumn(ColumnDataType = "nvarchar(20)")]
        public string user_code { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        [SugarColumn(ColumnDataType = "nvarchar(50)")]
        public string user_password { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [SugarColumn(ColumnDataType = "nvarchar(20)")]
        public string user_name { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        [SugarColumn(ColumnDataType = "nvarchar(5)")]
        public string sex { get; set; }
        /// <summary>
        /// 联系方式
        /// </summary>
        [SugarColumn(ColumnDataType = "nvarchar(20)")]
        public string phone { get; set; }
        /// <summary>
        /// 权限列表
        /// </summary>
        [Navigate(typeof(UserRoleMapping),nameof(UserRoleMapping.user_id),nameof(UserRoleMapping.role_id))]
        public List<Role>? Roles { get; set; }
    }
}